// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvedkmtjynhgsuxukxjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2ZWRrbXRqeW5oZ3N1eHVreGpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1Mjk4MjUsImV4cCI6MjA4NTEwNTgyNX0.ynltAo8KM4HuBzO5hyfkjlkVonuJUaUFp0djpArhhnY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});